import { NextResponse } from "next/server";
import connectToDatabase from "@/lib/db";
import ExamSession from "@/models/ExamSession";
import CandidateResponse from "@/models/CandidateResponse";
import Question from "@/models/Question";
import { handleApiError } from "@/lib/apiUtils";
import { generateWithGemini } from "@/lib/gemini";

// POST /api/session/[id]/analyze-answers
// Runs AI-generation detection on all text/code answers for a session.
// Stores results in session.answerAnalysis and returns them.
export async function POST(
    _req: Request,
    { params }: { params: Promise<{ id: string }> }
) {
    try {
        await connectToDatabase();
        const { id } = await params;

        const session = await ExamSession.findById(id).select(
            "examId answerAnalysis recruiterId"
        );
        if (!session) {
            return NextResponse.json({ message: "Session not found" }, { status: 404 });
        }

        // Fetch all candidate responses for this session
        const responses = await CandidateResponse.find({ sessionId: id })
            .select("questionId submittedCode writtenAnswer selectedOptionIndex")
            .lean();

        // Fetch question texts so we can give Gemini context
        const questionIds = responses.map((r) => r.questionId);
        const questions = await Question.find({ _id: { $in: questionIds } })
            .select("_id text type")
            .lean();

        interface LeanQuestion { _id: { toString(): string }; text: string; type: string }
        interface LeanResponse {
            questionId: { toString(): string };
            submittedCode?: string;
            writtenAnswer?: string;
            selectedOptionIndex?: number;
        }

        const questionMap = new Map<string, LeanQuestion>();
        (questions as unknown as LeanQuestion[]).forEach((q) =>
            questionMap.set(q._id.toString(), q)
        );

        const analysisResults: {
            questionId: string;
            aiProbability: number;
            reasoning: string;
            flagged: boolean;
        }[] = [];

        for (const resp of responses as unknown as LeanResponse[]) {
            const qId = resp.questionId.toString();
            const q = questionMap.get(qId);
            if (!q) continue;

            // Only analyse text/code answers — skip pure MCQ (no text submitted)
            const answerText = resp.submittedCode ?? resp.writtenAnswer ?? "";
            if (!answerText.trim() || resp.selectedOptionIndex !== undefined) continue;

            const prompt = `You are an AI-generated content detector specialised in exam integrity analysis.

Question: ${q.text}
Candidate answer:
\`\`\`
${answerText.slice(0, 2000)}
\`\`\`

Assess the probability (0.0–1.0) that this answer was generated by an AI (e.g. ChatGPT, Copilot, Gemini) rather than written by a human candidate.

Consider: unnaturally perfect structure, lack of personal reasoning, overly formal language, absence of typical human errors, copy-paste patterns, and verbosity typical of LLM output.

Respond with a JSON object (no markdown fences) with exactly these keys:
- "aiProbability": number 0.0 to 1.0
- "reasoning": one sentence explaining the main indicator

Only output the JSON object.`;

            try {
                const raw = await generateWithGemini(prompt);
                const clean = raw.replace(/```json|```/g, "").trim();
                const parsed = JSON.parse(clean) as { aiProbability: number; reasoning: string };
                const prob = Math.max(0, Math.min(1, Number(parsed.aiProbability) || 0));

                analysisResults.push({
                    questionId: qId,
                    aiProbability: prob,
                    reasoning: parsed.reasoning ?? "",
                    flagged: prob >= 0.7,
                });
            } catch {
                // Skip this answer if Gemini call fails
            }
        }

        if (analysisResults.length > 0) {
            session.answerAnalysis = analysisResults;
            await session.save();
        }

        return NextResponse.json({
            message: "Analysis complete",
            analysed: analysisResults.length,
            results: analysisResults,
        });
    } catch (error: unknown) {
        return handleApiError(error);
    }
}
